package resolver

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.63

import (
	"TestGoLandProject/graph/model"
	"context"
	"fmt"
)

// GetMyAuthData is the resolver for the getMyAuthData field.
func (r *queryResolver) GetMyAuthData(ctx context.Context) ([]*model.AuthData, error) {
	panic(fmt.Errorf("not implemented: GetMyAuthData - getMyAuthData"))
}
