package resolver

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.63

import (
	"TestGoLandProject/graph/model"
	"context"
	"fmt"
)

// GetCatalog is the resolver for the getCatalog field.
func (r *queryResolver) GetCatalog(ctx context.Context, catalog *model.Catalogs) (*model.Catalog, error) {
	panic(fmt.Errorf("not implemented: GetCatalog - getCatalog"))
}

// GetCatalogItems is the resolver for the getCatalogItems field.
func (r *queryResolver) GetCatalogItems(ctx context.Context, catalog *model.Catalogs) ([]*model.CatalogItem, error) {
	panic(fmt.Errorf("not implemented: GetCatalogItems - getCatalogItems"))
}

// GetCatalogItem is the resolver for the getCatalogItem field.
func (r *queryResolver) GetCatalogItem(ctx context.Context, catalogItemCode string) (*model.CatalogItem, error) {
	panic(fmt.Errorf("not implemented: GetCatalogItem - getCatalogItem"))
}
