package resolver

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.63

import (
	"TestGoLandProject/graph/model"
	"context"
	"fmt"
)

// GetMyActiveComplaints is the resolver for the getMyActiveComplaints field.
func (r *queryResolver) GetMyActiveComplaints(ctx context.Context) ([]model.Complaint, error) {
	panic(fmt.Errorf("not implemented: GetMyActiveComplaints - getMyActiveComplaints"))
}

// GetMyClosedComplaints is the resolver for the getMyClosedComplaints field.
func (r *queryResolver) GetMyClosedComplaints(ctx context.Context) ([]model.Complaint, error) {
	panic(fmt.Errorf("not implemented: GetMyClosedComplaints - getMyClosedComplaints"))
}

// GetMyRefusedComplaints is the resolver for the getMyRefusedComplaints field.
func (r *queryResolver) GetMyRefusedComplaints(ctx context.Context) ([]model.Complaint, error) {
	panic(fmt.Errorf("not implemented: GetMyRefusedComplaints - getMyRefusedComplaints"))
}
