package resolver

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.63

import (
	"TestGoLandProject/graph/model"
	"context"
	"fmt"
)

// LikeGameFindPostCommentPost is the resolver for the likeGameFindPostCommentPost field.
func (r *mutationResolver) LikeGameFindPostCommentPost(ctx context.Context, likeData model.GameFindPostCommentLikeData) (*model.LikeState, error) {
	panic(fmt.Errorf("not implemented: LikeGameFindPostCommentPost - likeGameFindPostCommentPost"))
}
