package resolver

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.63

import (
	"TestGoLandProject/graph/model"
	"context"
	"fmt"
)

// CreateGameFindPostComplaint is the resolver for the createGameFindPostComplaint field.
func (r *mutationResolver) CreateGameFindPostComplaint(ctx context.Context, gameFindPostIDHolder model.IDHolder, newComplaint model.NewGameFindPostComplaint) (*model.GameFindPostComplaint, error) {
	panic(fmt.Errorf("not implemented: CreateGameFindPostComplaint - createGameFindPostComplaint"))
}

// DeleteGameFindPostComplaint is the resolver for the deleteGameFindPostComplaint field.
func (r *mutationResolver) DeleteGameFindPostComplaint(ctx context.Context, complaintIDHolder model.IDHolder) (*model.DeleteResult, error) {
	panic(fmt.Errorf("not implemented: DeleteGameFindPostComplaint - deleteGameFindPostComplaint"))
}

// GetMyActiveGameFindPostComplaints is the resolver for the getMyActiveGameFindPostComplaints field.
func (r *queryResolver) GetMyActiveGameFindPostComplaints(ctx context.Context) ([]*model.GameFindPostComplaint, error) {
	panic(fmt.Errorf("not implemented: GetMyActiveGameFindPostComplaints - getMyActiveGameFindPostComplaints"))
}

// GetMyClosedGameFindPostComplaints is the resolver for the getMyClosedGameFindPostComplaints field.
func (r *queryResolver) GetMyClosedGameFindPostComplaints(ctx context.Context) ([]*model.GameFindPostComplaint, error) {
	panic(fmt.Errorf("not implemented: GetMyClosedGameFindPostComplaints - getMyClosedGameFindPostComplaints"))
}

// GetMyRefusedGameFindPostComplaints is the resolver for the getMyRefusedGameFindPostComplaints field.
func (r *queryResolver) GetMyRefusedGameFindPostComplaints(ctx context.Context) ([]*model.GameFindPostComplaint, error) {
	panic(fmt.Errorf("not implemented: GetMyRefusedGameFindPostComplaints - getMyRefusedGameFindPostComplaints"))
}
