package resolver

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.63

import (
	"TestGoLandProject/graph/model"
	"context"
	"fmt"
)

// CreateGameFindPostCommentComplaint is the resolver for the createGameFindPostCommentComplaint field.
func (r *mutationResolver) CreateGameFindPostCommentComplaint(ctx context.Context, gameFindPostCommentIDHolder model.IDHolder, newComplaint model.NewGameFindPostCommentComplaint) (*model.GameFindPostCommentComplaint, error) {
	panic(fmt.Errorf("not implemented: CreateGameFindPostCommentComplaint - createGameFindPostCommentComplaint"))
}

// DeleteGameFindPostCommentComplaint is the resolver for the deleteGameFindPostCommentComplaint field.
func (r *mutationResolver) DeleteGameFindPostCommentComplaint(ctx context.Context, complaintIDHolder model.IDHolder) (*model.DeleteResult, error) {
	panic(fmt.Errorf("not implemented: DeleteGameFindPostCommentComplaint - deleteGameFindPostCommentComplaint"))
}

// GetMyActiveGameFindPostCommentComplaints is the resolver for the getMyActiveGameFindPostCommentComplaints field.
func (r *queryResolver) GetMyActiveGameFindPostCommentComplaints(ctx context.Context) ([]*model.GameFindPostCommentComplaint, error) {
	panic(fmt.Errorf("not implemented: GetMyActiveGameFindPostCommentComplaints - getMyActiveGameFindPostCommentComplaints"))
}

// GetMyClosedGameFindPostCommentComplaints is the resolver for the getMyClosedGameFindPostCommentComplaints field.
func (r *queryResolver) GetMyClosedGameFindPostCommentComplaints(ctx context.Context) ([]*model.GameFindPostCommentComplaint, error) {
	panic(fmt.Errorf("not implemented: GetMyClosedGameFindPostCommentComplaints - getMyClosedGameFindPostCommentComplaints"))
}

// GetMyRefusedGameFindPostCommentComplaints is the resolver for the getMyRefusedGameFindPostCommentComplaints field.
func (r *queryResolver) GetMyRefusedGameFindPostCommentComplaints(ctx context.Context) ([]*model.GameFindPostCommentComplaint, error) {
	panic(fmt.Errorf("not implemented: GetMyRefusedGameFindPostCommentComplaints - getMyRefusedGameFindPostCommentComplaints"))
}
