package resolver

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.63

import (
	"TestGoLandProject/graph/model"
	"context"
	"fmt"
)

// CreateGameFindPostComment is the resolver for the createGameFindPostComment field.
func (r *mutationResolver) CreateGameFindPostComment(ctx context.Context, gameFindPostIDHolder model.IDHolder, comment model.NewGameFindPostComment) (*model.GameFindPostComment, error) {
	panic(fmt.Errorf("not implemented: CreateGameFindPostComment - createGameFindPostComment"))
}

// DeleteGameFindPostComment is the resolver for the deleteGameFindPostComment field.
func (r *mutationResolver) DeleteGameFindPostComment(ctx context.Context, commentID model.IDHolder) (*model.DeleteResult, error) {
	panic(fmt.Errorf("not implemented: DeleteGameFindPostComment - deleteGameFindPostComment"))
}
