package resolver

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.63

import (
	"TestGoLandProject/graph/model"
	"context"
	"fmt"
)

// CreateGameFindPost is the resolver for the createGameFindPost field.
func (r *mutationResolver) CreateGameFindPost(ctx context.Context, newGameFindPost model.NewGameFindPost) (*model.GameFindPost, error) {
	panic(fmt.Errorf("not implemented: CreateGameFindPost - createGameFindPost"))
}

// UpdateGameFindPost is the resolver for the updateGameFindPost field.
func (r *mutationResolver) UpdateGameFindPost(ctx context.Context, newGameFindPostData model.UpdateGameFindPost) (*model.GameFindPost, error) {
	panic(fmt.Errorf("not implemented: UpdateGameFindPost - updateGameFindPost"))
}

// DeleteGameFindPost is the resolver for the deleteGameFindPost field.
func (r *mutationResolver) DeleteGameFindPost(ctx context.Context, gameFindPostIDHolder model.IDHolder) (*model.DeleteResult, error) {
	panic(fmt.Errorf("not implemented: DeleteGameFindPost - deleteGameFindPost"))
}

// GetGameFindPost is the resolver for the getGameFindPost field.
func (r *queryResolver) GetGameFindPost(ctx context.Context, gameFindPostIDHolder model.IDHolder) (*model.GameFindPost, error) {
	panic(fmt.Errorf("not implemented: GetGameFindPost - getGameFindPost"))
}

// GetMyGameFindPosts is the resolver for the getMyGameFindPosts field.
func (r *queryResolver) GetMyGameFindPosts(ctx context.Context, paginationSettings model.ListPaginationSettings) ([]*model.GameFindPost, error) {
	panic(fmt.Errorf("not implemented: GetMyGameFindPosts - getMyGameFindPosts"))
}

// GetUserGameFindPosts is the resolver for the getUserGameFindPosts field.
func (r *queryResolver) GetUserGameFindPosts(ctx context.Context, userIDHolder model.IDHolder, paginationSettings model.ListPaginationSettings) ([]*model.GameFindPost, error) {
	panic(fmt.Errorf("not implemented: GetUserGameFindPosts - getUserGameFindPosts"))
}

// GetRecommendedGameFindPosts is the resolver for the getRecommendedGameFindPosts field.
func (r *queryResolver) GetRecommendedGameFindPosts(ctx context.Context, paginationSettings model.ListPaginationSettings) ([]*model.GameFindPost, error) {
	panic(fmt.Errorf("not implemented: GetRecommendedGameFindPosts - getRecommendedGameFindPosts"))
}
