package resolver

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.63

import (
	graph "TestGoLandProject/graph/generated"
	"context"
	"fmt"
)

// Mutation is the resolver for the mutation field.
func (r *mutationResolver) Mutation(ctx context.Context) (*string, error) {
	panic(fmt.Errorf("not implemented: Mutation - mutation"))
}

// Query is the resolver for the query field.
func (r *queryResolver) Query(ctx context.Context) (*string, error) {
	panic(fmt.Errorf("not implemented: Query - query"))
}

// Mutation returns graph.MutationResolver implementation.
func (r *Resolver) Mutation() graph.MutationResolver { return &mutationResolver{r} }

// Query returns graph.QueryResolver implementation.
func (r *Resolver) Query() graph.QueryResolver { return &queryResolver{r} }

type mutationResolver struct{ *Resolver }
type queryResolver struct{ *Resolver }
