package resolver

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.63

import (
	"TestGoLandProject/graph/model"
	"context"
	"fmt"
)

// CreatePostComment is the resolver for the createPostComment field.
func (r *mutationResolver) CreatePostComment(ctx context.Context, postIDHolder model.IDHolder, comment model.NewPostComment) (*model.PostComment, error) {
	panic(fmt.Errorf("not implemented: CreatePostComment - createPostComment"))
}

// DeletePostComment is the resolver for the deletePostComment field.
func (r *mutationResolver) DeletePostComment(ctx context.Context, commentIDHolder model.IDHolder) (*model.DeleteResult, error) {
	panic(fmt.Errorf("not implemented: DeletePostComment - deletePostComment"))
}
