package resolver

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.63

import (
	"TestGoLandProject/graph/model"
	"context"
	"fmt"
)

// AddNewAvatar is the resolver for the addNewAvatar field.
func (r *mutationResolver) AddNewAvatar(ctx context.Context, avatarImageID model.IDHolder) (*model.Image, error) {
	panic(fmt.Errorf("not implemented: AddNewAvatar - addNewAvatar"))
}

// DeleteAvatar is the resolver for the deleteAvatar field.
func (r *mutationResolver) DeleteAvatar(ctx context.Context, avatarImageID model.IDHolder) (*model.DeleteResult, error) {
	panic(fmt.Errorf("not implemented: DeleteAvatar - deleteAvatar"))
}

// MyAvatars is the resolver for the myAvatars field.
func (r *queryResolver) MyAvatars(ctx context.Context) ([]*model.Image, error) {
	panic(fmt.Errorf("not implemented: MyAvatars - myAvatars"))
}

// UserAvatars is the resolver for the userAvatars field.
func (r *queryResolver) UserAvatars(ctx context.Context, userIDHolder model.IDHolder) ([]*model.Image, error) {
	panic(fmt.Errorf("not implemented: UserAvatars - userAvatars"))
}
