// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type CreateUser struct {
	Nickname   string `json:"nickname"`
	Login      string `json:"login"`
	Password   string `json:"password"`
	DeviceName string `json:"deviceName"`
}

type Mutation struct {
}

type NewUser struct {
	ID       string `json:"id"`
	Nickname string `json:"nickname"`
	Login    string `json:"login"`
	Password string `json:"password"`
	Token    string `json:"token"`
}

type Query struct {
}

type UpdateUser struct {
	ID       string `json:"id"`
	Nickname string `json:"nickname"`
	Login    string `json:"login"`
	Password string `json:"password"`
}

type User struct {
	ID        string `json:"id"`
	Nickname  string `json:"nickname"`
	Login     string `json:"login"`
	Password  string `json:"password"`
	CreatedAt int    `json:"createdAt"`
	EditedAt  *int   `json:"editedAt,omitempty"`
	DeletedAt *int   `json:"deletedAt,omitempty"`
	IsAdmin   bool   `json:"isAdmin"`
}

type UserID struct {
	ID string `json:"id"`
}
