// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type CreateUser struct {
	Nickname string `json:"nickname"`
	Login    string `json:"login"`
	Password string `json:"password"`
}

type Mutation struct {
}

type Query struct {
}

type UpdateUser struct {
	ID       string `json:"id"`
	Nickname string `json:"nickname"`
	Login    string `json:"login"`
	Password string `json:"password"`
}

type User struct {
	ID       string `json:"id"`
	Nickname string `json:"nickname"`
	Login    string `json:"login"`
	Password string `json:"password"`
}

type UserID struct {
	ID string `json:"id"`
}
